### ISSUE TITLE
Handle empty question

### ISSUE THREAD

**Issue by alex-wilmer** [torontojs/slack-overflow#1]
have a default here https://github.com/torontojs/slack-overflow/blob/master/src/ask.js#L5

but really it should reply with a helpful message

**Comment by GeorgiosP** [comment]
Looking for a more graceful reply when there is no question? if no one takes this I'd like to take it on

**Comment by mihok** [comment]
It's all yours @GeorgiosP !

**Comment by alex-wilmer** [comment]
thanks @GeorgiosP 

https://github.com/torontojs/slack-overflow/commit/96d65deea8cf48faf63acc22bdd50e27b51bb9c8
